# Generated by Django 4.2 on 2025-04-09 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='vendor_profile',
        ),
    ]
