# Generated by Django 4.2 on 2025-04-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_emailverificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationcode',
            name='attemps',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
