# Generated by Django 4.2 on 2025-04-08 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(db_index=True, max_length=100, verbose_name='store name')),
                ('store_logo', models.ImageField(blank=True, null=True, upload_to='store_logos/', verbose_name='store logo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('is_verified', models.BooleanField(default=False, verbose_name='verified')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'vendor',
                'verbose_name_plural': 'vendors',
            },
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['store_name'], name='vendors_ven_store_n_ea5b94_idx'),
        ),
    ]
