# Generated by Django 4.2 on 2025-04-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_vendor_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='store_name',
            field=models.CharField(db_index=True, max_length=500, verbose_name='store name'),
        ),
    ]
