# Generated by Django 4.2 on 2025-04-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_alter_vendor_store_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='store_name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='store name'),
        ),
    ]
