# Generated by Django 4.2 on 2025-04-09 17:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_alter_vendor_options_vendor_phone_vendor_rating_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ['-created_at'], 'verbose_name': 'vendor', 'verbose_name_plural': 'vendors'},
        ),
        migrations.RemoveIndex(
            model_name='vendor',
            name='vendors_ven_store_n_ea5b94_idx',
        ),
        migrations.RemoveIndex(
            model_name='vendor',
            name='vendors_ven_rating_1e84ed_idx',
        ),
        migrations.AlterField(
            model_name='vendor',
            name='store_logo',
            field=models.ImageField(blank=True, null=True, upload_to='store_logos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='store logo'),
        ),
    ]
